// Standardized list of insurance providers in Jordan
export const INSURANCE_PROVIDERS = [
  'Civil Health Insurance',
  'Royal Medical Services (Military Insurance Fund)',
  'Social Security Corporation (Health Insurance Program)',
  'UNRWA Health Services',
  'King Hussein Cancer Center – Cancer Care Insurance (CCI)',
  'Jordan Insurance Company',
  'Jordan International Insurance (Newton Insurance)',
  'Al Manara Islamic Insurance Company',
  'Al Nisr Al Arabi Insurance Company',
  'American Life Insurance Company (MetLife Jordan)',
  'Arab Assurers Insurance Company',
  'Arab Jordanian Insurance Group (AJIG)',
  'Arabia Insurance Company – Jordan',
  'Delta Insurance',
  'Euro Arab Insurance Group',
  'Gulf Insurance Group – Jordan (GIG Jordan)',
  'Jerusalem Insurance Company (JICO)',
  'MedGulf Insurance – Jordan',
  'Middle East Insurance Company (MEICO)',
  'National Insurance Company',
  'Solidarity – First Insurance Company',
  'Islamic Insurance Company',
  'United Insurance Company PLC',
  'Watania National Insurance Company',
  'Arab Orient Insurance (Gig Arabia)',
  'National Health Insurance Administration (NatHealth)',
  'Jordan Engineers Association (Health Insurance Fund)',
  'Jordanian Bar Association (Health Insurance Unit)',
  'Jordanian Medical Association (Health Insurance Program)',
  'Jordanian Dental Association (Health Coverage Program)',
  'University Hospitals\' Health Insurance Programs',
  'Jordan Teachers Association (Health Fund)',
  'Public Universities Insurance Funds (e.g., University of Jordan, Yarmouk University)',
  'Royal Court Health Coverage Program',
  'Civil Defense Health Fund',
  'Public Security Directorate Health Fund',
  'Ministry of Health Employees\' Insurance',
  'Jordan Phosphate Mines Company Health Insurance',
  'Arab Potash Company Health Insurance',
  'Jordan Petroleum Refinery Health Fund',
  'Telecommunications Health Insurance (e.g., Orange, Zain, Umniah employee health funds)',
  'Greater Amman Municipality Health Insurance Fund',
  'Jordan Electric Power Company Health Insurance',
  'Engineers Housing Cooperative Health Program',
  'Jordan Nurses and Midwives Council Health Program',
  'Jordan Pharmacists Association Health Fund',
  'Jordan Cooperative Corporation Health Scheme',
  'Professional Associations Unified Insurance Fund',
  'National Aid Fund Health Coverage',
];

