package com.MediConnect.EntryRelated.entities.enums;

public enum MentalHealthCondition {
    NO_KNOWN_MENTAL_HEALTH_CONDITIONS,
    DEPRESSION,
    ANXIETY_DISORDER_GENERALIZED_ANXIETY_DISORDER,
    BIPOLAR_DISORDER,
    POST_TRAUMATIC_STRESS_DISORDER_PTSD,
    OBSESSIVE_COMPULSIVE_DISORDER_OCD,
    SCHIZOPHRENIA,
    SCHIZOAFFECTIVE_DISORDER,
    ATTENTION_DEFICIT_HYPERACTIVITY_DISORDER_ADHD,
    AUTISM_SPECTRUM_DISORDER_ASD,
    PANIC_DISORDER,
    SOCIAL_ANXIETY_DISORDER,
    EATING_DISORDER_E_G_ANOREXIA_BULIMIA,
    PERSONALITY_DISORDER_E_G_BORDERLINE_PERSONALITY_DISORDER,
    SUBSTANCE_USE_DISORDER_ALCOHOL_OR_DRUGS,
    INSOMNIA_CHRONIC_SLEEP_DISORDER,
    DEMENTIA_COGNITIVE_DECLINE,
    ALZHEIMER_DISEASE,
    ADJUSTMENT_DISORDER,
    PSYCHOTIC_DISORDER_OTHER_THAN_SCHIZOPHRENIA,
    OTHER,
    PREFER_NOT_TO_SAY;
}
